//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSign.WebAPI.RpostService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errCodeField;
        
        private string reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("ErrCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string isOnTrialField;
        
        private string respCodeField;
        
        private string responseField;
        
        private string trialsLeftField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string IsOnTrial {
            get {
                return this.isOnTrialField;
            }
            set {
                this.isOnTrialField = value;
                this.RaisePropertyChanged("IsOnTrial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RespCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("RespCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string TrialsLeft {
            get {
                return this.trialsLeftField;
            }
            set {
                this.trialsLeftField = value;
                this.RaisePropertyChanged("TrialsLeft");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.rpost.com", ConfigurationName="RpostService.RPostService")]
    public interface RPostService {
        
        // CODEGEN: Parameter 'RegisterUserResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/RegisterUser", ReplyAction="http://service.rpost.com/RPostService/RegisterUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/RegisterUserServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.RegisterUserResponse RegisterUser(eSign.WebAPI.RpostService.RegisterUserRequest request);
        
        // CODEGEN: Parameter 'SendEmailResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/SendEmail", ReplyAction="http://service.rpost.com/RPostService/SendEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/SendEmailServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.SendEmailResponse SendEmail(eSign.WebAPI.RpostService.SendEmailRequest request);
        
        // CODEGEN: Parameter 'SendEmailFromStringResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/SendEmailFromString", ReplyAction="http://service.rpost.com/RPostService/SendEmailFromStringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/SendEmailFromStringServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.SendEmailFromStringResponse SendEmailFromString(eSign.WebAPI.RpostService.SendEmailFromStringRequest request);
        
        // CODEGEN: Parameter 'SendEmailFromBoxViaWCFClientResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/SendEmailFromBoxViaWCFClient", ReplyAction="http://service.rpost.com/RPostService/SendEmailFromBoxViaWCFClientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/SendEmailFromBoxViaWCFClientServiceExceptio" +
            "nFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientResponse SendEmailFromBoxViaWCFClient(eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (FileUploadMessage) of message FileUploadMessage does not match the default value (LoadAttachment)
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/LoadAttachment", ReplyAction="http://service.rpost.com/RPostService/LoadAttachmentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.FileUploadResponse LoadAttachment(eSign.WebAPI.RpostService.FileUploadMessage request);
        
        // CODEGEN: Parameter 'LoadAttachmentFromBase64Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/LoadAttachmentFromBase64", ReplyAction="http://service.rpost.com/RPostService/LoadAttachmentFromBase64Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.LoadAttachmentFromBase64Response LoadAttachmentFromBase64(eSign.WebAPI.RpostService.LoadAttachmentFromBase64Request request);
        
        // CODEGEN: Generating message contract since the wrapper name (FileUploadMessage) of message FileUploadMessage does not match the default value (LoadSignature)
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/LoadSignature", ReplyAction="http://service.rpost.com/RPostService/LoadSignatureResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.FileUploadResponse LoadSignature(eSign.WebAPI.RpostService.FileUploadMessage request);
        
        // CODEGEN: Parameter 'LoadSignatureFromBase64Result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/LoadSignatureFromBase64", ReplyAction="http://service.rpost.com/RPostService/LoadSignatureFromBase64Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.LoadSignatureFromBase64Response LoadSignatureFromBase64(eSign.WebAPI.RpostService.LoadSignatureFromBase64Request request);
        
        // CODEGEN: Parameter 'AuthenticateUserResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/AuthenticateUser", ReplyAction="http://service.rpost.com/RPostService/AuthenticateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/AuthenticateUserServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.AuthenticateUserResponse AuthenticateUser(eSign.WebAPI.RpostService.AuthenticateUserRequest request);
        
        // CODEGEN: Parameter 'AuthenticateEnterpriseResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/AuthenticateEnterprise", ReplyAction="http://service.rpost.com/RPostService/AuthenticateEnterpriseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/AuthenticateEnterpriseServiceExceptionFault" +
            "", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.AuthenticateEnterpriseResponse AuthenticateEnterprise(eSign.WebAPI.RpostService.AuthenticateEnterpriseRequest request);
        
        // CODEGEN: Parameter 'ForgotPasswordResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/ForgotPassword", ReplyAction="http://service.rpost.com/RPostService/ForgotPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/ForgotPasswordServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.ForgotPasswordResponse ForgotPassword(eSign.WebAPI.RpostService.ForgotPasswordRequest request);
        
        // CODEGEN: Parameter 'ChangePasswordResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/ChangePassword", ReplyAction="http://service.rpost.com/RPostService/ChangePasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/ChangePasswordServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.ChangePasswordResponse ChangePassword(eSign.WebAPI.RpostService.ChangePasswordRequest request);
        
        // CODEGEN: Parameter 'LogoutResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/Logout", ReplyAction="http://service.rpost.com/RPostService/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/LogoutServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.LogoutResponse Logout(eSign.WebAPI.RpostService.LogoutRequest request);
        
        // CODEGEN: Parameter 'ResendActivationLinkResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/ResendActivationLink", ReplyAction="http://service.rpost.com/RPostService/ResendActivationLinkResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/ResendActivationLinkServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.ResendActivationLinkResponse ResendActivationLink(eSign.WebAPI.RpostService.ResendActivationLinkRequest request);
        
        // CODEGEN: Parameter 'ChangeDisplayNameResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.rpost.com/RPostService/ChangeDisplayName", ReplyAction="http://service.rpost.com/RPostService/ChangeDisplayNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eSign.WebAPI.RpostService.ServiceException), Action="http://service.rpost.com/RPostService/ChangeDisplayNameServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eSign.WebAPI.RpostService.ChangeDisplayNameResponse ChangeDisplayName(eSign.WebAPI.RpostService.ChangeDisplayNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUser", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Brand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Lang;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayName;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(string UserID, string Password, string Brand, string Lang, string DisplayName) {
            this.UserID = UserID;
            this.Password = Password;
            this.Brand = Brand;
            this.Lang = Lang;
            this.DisplayName = DisplayName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RegisterUserResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse RegisterUserResult;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(eSign.WebAPI.RpostService.ServiceResponse RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmail", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class SendEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Xml.XmlElement MsgParms;
        
        public SendEmailRequest() {
        }
        
        public SendEmailRequest(string AuthKey, System.Xml.XmlElement MsgParms) {
            this.AuthKey = AuthKey;
            this.MsgParms = MsgParms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class SendEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse SendEmailResult;
        
        public SendEmailResponse() {
        }
        
        public SendEmailResponse(eSign.WebAPI.RpostService.ServiceResponse SendEmailResult) {
            this.SendEmailResult = SendEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailFromString", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class SendEmailFromStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgParms;
        
        public SendEmailFromStringRequest() {
        }
        
        public SendEmailFromStringRequest(string AuthKey, string MsgParms) {
            this.AuthKey = AuthKey;
            this.MsgParms = MsgParms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailFromStringResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class SendEmailFromStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse SendEmailFromStringResult;
        
        public SendEmailFromStringResponse() {
        }
        
        public SendEmailFromStringResponse(eSign.WebAPI.RpostService.ServiceResponse SendEmailFromStringResult) {
            this.SendEmailFromStringResult = SendEmailFromStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailFromBoxViaWCFClient", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class SendEmailFromBoxViaWCFClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MsgParms;
        
        public SendEmailFromBoxViaWCFClientRequest() {
        }
        
        public SendEmailFromBoxViaWCFClientRequest(string UserID, string Password, string MsgParms) {
            this.UserID = UserID;
            this.Password = Password;
            this.MsgParms = MsgParms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendEmailFromBoxViaWCFClientResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class SendEmailFromBoxViaWCFClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SendEmailFromBoxViaWCFClientResult;
        
        public SendEmailFromBoxViaWCFClientResponse() {
        }
        
        public SendEmailFromBoxViaWCFClientResponse(string SendEmailFromBoxViaWCFClientResult) {
            this.SendEmailFromBoxViaWCFClientResult = SendEmailFromBoxViaWCFClientResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class FileUploadRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authKeyField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AuthKey {
            get {
                return this.authKeyField;
            }
            set {
                this.authKeyField = value;
                this.RaisePropertyChanged("AuthKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.rpost.com")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.FileUploadRequest FileMeta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(eSign.WebAPI.RpostService.FileUploadRequest FileMeta, System.IO.Stream FileByteStream) {
            this.FileMeta = FileMeta;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class FileUploadResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://service.rpost.com")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse Response;
        
        public FileUploadResponse() {
        }
        
        public FileUploadResponse(eSign.WebAPI.RpostService.ServiceResponse Response) {
            this.Response = Response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAttachmentFromBase64", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class LoadAttachmentFromBase64Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileContent;
        
        public LoadAttachmentFromBase64Request() {
        }
        
        public LoadAttachmentFromBase64Request(string AuthKey, string FileName, string FileContent) {
            this.AuthKey = AuthKey;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadAttachmentFromBase64Response", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class LoadAttachmentFromBase64Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse LoadAttachmentFromBase64Result;
        
        public LoadAttachmentFromBase64Response() {
        }
        
        public LoadAttachmentFromBase64Response(eSign.WebAPI.RpostService.ServiceResponse LoadAttachmentFromBase64Result) {
            this.LoadAttachmentFromBase64Result = LoadAttachmentFromBase64Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadSignatureFromBase64", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class LoadSignatureFromBase64Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileContent;
        
        public LoadSignatureFromBase64Request() {
        }
        
        public LoadSignatureFromBase64Request(string AuthKey, string FileName, string FileContent) {
            this.AuthKey = AuthKey;
            this.FileName = FileName;
            this.FileContent = FileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoadSignatureFromBase64Response", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class LoadSignatureFromBase64Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse LoadSignatureFromBase64Result;
        
        public LoadSignatureFromBase64Response() {
        }
        
        public LoadSignatureFromBase64Response(eSign.WebAPI.RpostService.ServiceResponse LoadSignatureFromBase64Result) {
            this.LoadSignatureFromBase64Result = LoadSignatureFromBase64Result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class AuthorizationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorizationKeyField;
        
        private string messageField;
        
        private string respCodeField;
        
        private string statusField;
        
        private string trialsLeftField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AuthorizationKey {
            get {
                return this.authorizationKeyField;
            }
            set {
                this.authorizationKeyField = value;
                this.RaisePropertyChanged("AuthorizationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string RespCode {
            get {
                return this.respCodeField;
            }
            set {
                this.respCodeField = value;
                this.RaisePropertyChanged("RespCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string TrialsLeft {
            get {
                return this.trialsLeftField;
            }
            set {
                this.trialsLeftField = value;
                this.RaisePropertyChanged("TrialsLeft");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUser", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(string UserID, string Password) {
            this.UserID = UserID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateUserResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.AuthorizationResponse AuthenticateUserResult;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(eSign.WebAPI.RpostService.AuthorizationResponse AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateEnterprise", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class AuthenticateEnterpriseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EnterpriseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string APIKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerAccount;
        
        public AuthenticateEnterpriseRequest() {
        }
        
        public AuthenticateEnterpriseRequest(string EnterpriseID, string Password, string APIKey, string CustomerAccount) {
            this.EnterpriseID = EnterpriseID;
            this.Password = Password;
            this.APIKey = APIKey;
            this.CustomerAccount = CustomerAccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthenticateEnterpriseResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class AuthenticateEnterpriseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.AuthorizationResponse AuthenticateEnterpriseResult;
        
        public AuthenticateEnterpriseResponse() {
        }
        
        public AuthenticateEnterpriseResponse(eSign.WebAPI.RpostService.AuthorizationResponse AuthenticateEnterpriseResult) {
            this.AuthenticateEnterpriseResult = AuthenticateEnterpriseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForgotPassword", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ForgotPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserId;
        
        public ForgotPasswordRequest() {
        }
        
        public ForgotPasswordRequest(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ForgotPasswordResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ForgotPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.AuthorizationResponse ForgotPasswordResult;
        
        public ForgotPasswordResponse() {
        }
        
        public ForgotPasswordResponse(eSign.WebAPI.RpostService.AuthorizationResponse ForgotPasswordResult) {
            this.ForgotPasswordResult = ForgotPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePassword", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OldPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NewPassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ConfirmPassword;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(string UserId, string OldPassword, string NewPassword, string ConfirmPassword) {
            this.UserId = UserId;
            this.OldPassword = OldPassword;
            this.NewPassword = NewPassword;
            this.ConfirmPassword = ConfirmPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangePasswordResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.AuthorizationResponse ChangePasswordResult;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(eSign.WebAPI.RpostService.AuthorizationResponse ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Logout", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class LogoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthKey;
        
        public LogoutRequest() {
        }
        
        public LogoutRequest(string AuthKey) {
            this.AuthKey = AuthKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LogoutResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class LogoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.AuthorizationResponse LogoutResult;
        
        public LogoutResponse() {
        }
        
        public LogoutResponse(eSign.WebAPI.RpostService.AuthorizationResponse LogoutResult) {
            this.LogoutResult = LogoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResendActivationLink", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ResendActivationLinkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserId;
        
        public ResendActivationLinkRequest() {
        }
        
        public ResendActivationLinkRequest(string UserId) {
            this.UserId = UserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResendActivationLinkResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ResendActivationLinkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.AuthorizationResponse ResendActivationLinkResult;
        
        public ResendActivationLinkResponse() {
        }
        
        public ResendActivationLinkResponse(eSign.WebAPI.RpostService.AuthorizationResponse ResendActivationLinkResult) {
            this.ResendActivationLinkResult = ResendActivationLinkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeDisplayName", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ChangeDisplayNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AuthKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayName;
        
        public ChangeDisplayNameRequest() {
        }
        
        public ChangeDisplayNameRequest(string AuthKey, string DisplayName) {
            this.AuthKey = AuthKey;
            this.DisplayName = DisplayName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChangeDisplayNameResponse", WrapperNamespace="http://service.rpost.com", IsWrapped=true)]
    public partial class ChangeDisplayNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.rpost.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public eSign.WebAPI.RpostService.ServiceResponse ChangeDisplayNameResult;
        
        public ChangeDisplayNameResponse() {
        }
        
        public ChangeDisplayNameResponse(eSign.WebAPI.RpostService.ServiceResponse ChangeDisplayNameResult) {
            this.ChangeDisplayNameResult = ChangeDisplayNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RPostServiceChannel : eSign.WebAPI.RpostService.RPostService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RPostServiceClient : System.ServiceModel.ClientBase<eSign.WebAPI.RpostService.RPostService>, eSign.WebAPI.RpostService.RPostService {
        
        public RPostServiceClient() {
        }
        
        public RPostServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RPostServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.RegisterUserResponse eSign.WebAPI.RpostService.RPostService.RegisterUser(eSign.WebAPI.RpostService.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse RegisterUser(string UserID, string Password, string Brand, string Lang, string DisplayName) {
            eSign.WebAPI.RpostService.RegisterUserRequest inValue = new eSign.WebAPI.RpostService.RegisterUserRequest();
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.Brand = Brand;
            inValue.Lang = Lang;
            inValue.DisplayName = DisplayName;
            eSign.WebAPI.RpostService.RegisterUserResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).RegisterUser(inValue);
            return retVal.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.SendEmailResponse eSign.WebAPI.RpostService.RPostService.SendEmail(eSign.WebAPI.RpostService.SendEmailRequest request) {
            return base.Channel.SendEmail(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse SendEmail(string AuthKey, System.Xml.XmlElement MsgParms) {
            eSign.WebAPI.RpostService.SendEmailRequest inValue = new eSign.WebAPI.RpostService.SendEmailRequest();
            inValue.AuthKey = AuthKey;
            inValue.MsgParms = MsgParms;
            eSign.WebAPI.RpostService.SendEmailResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).SendEmail(inValue);
            return retVal.SendEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.SendEmailFromStringResponse eSign.WebAPI.RpostService.RPostService.SendEmailFromString(eSign.WebAPI.RpostService.SendEmailFromStringRequest request) {
            return base.Channel.SendEmailFromString(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse SendEmailFromString(string AuthKey, string MsgParms) {
            eSign.WebAPI.RpostService.SendEmailFromStringRequest inValue = new eSign.WebAPI.RpostService.SendEmailFromStringRequest();
            inValue.AuthKey = AuthKey;
            inValue.MsgParms = MsgParms;
            eSign.WebAPI.RpostService.SendEmailFromStringResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).SendEmailFromString(inValue);
            return retVal.SendEmailFromStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientResponse eSign.WebAPI.RpostService.RPostService.SendEmailFromBoxViaWCFClient(eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientRequest request) {
            return base.Channel.SendEmailFromBoxViaWCFClient(request);
        }
        
        public string SendEmailFromBoxViaWCFClient(string UserID, string Password, string MsgParms) {
            eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientRequest inValue = new eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientRequest();
            inValue.UserID = UserID;
            inValue.Password = Password;
            inValue.MsgParms = MsgParms;
            eSign.WebAPI.RpostService.SendEmailFromBoxViaWCFClientResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).SendEmailFromBoxViaWCFClient(inValue);
            return retVal.SendEmailFromBoxViaWCFClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.FileUploadResponse eSign.WebAPI.RpostService.RPostService.LoadAttachment(eSign.WebAPI.RpostService.FileUploadMessage request) {
            return base.Channel.LoadAttachment(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse LoadAttachment(eSign.WebAPI.RpostService.FileUploadRequest FileMeta, System.IO.Stream FileByteStream) {
            eSign.WebAPI.RpostService.FileUploadMessage inValue = new eSign.WebAPI.RpostService.FileUploadMessage();
            inValue.FileMeta = FileMeta;
            inValue.FileByteStream = FileByteStream;
            eSign.WebAPI.RpostService.FileUploadResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).LoadAttachment(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.LoadAttachmentFromBase64Response eSign.WebAPI.RpostService.RPostService.LoadAttachmentFromBase64(eSign.WebAPI.RpostService.LoadAttachmentFromBase64Request request) {
            return base.Channel.LoadAttachmentFromBase64(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse LoadAttachmentFromBase64(string AuthKey, string FileName, string FileContent) {
            eSign.WebAPI.RpostService.LoadAttachmentFromBase64Request inValue = new eSign.WebAPI.RpostService.LoadAttachmentFromBase64Request();
            inValue.AuthKey = AuthKey;
            inValue.FileName = FileName;
            inValue.FileContent = FileContent;
            eSign.WebAPI.RpostService.LoadAttachmentFromBase64Response retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).LoadAttachmentFromBase64(inValue);
            return retVal.LoadAttachmentFromBase64Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.FileUploadResponse eSign.WebAPI.RpostService.RPostService.LoadSignature(eSign.WebAPI.RpostService.FileUploadMessage request) {
            return base.Channel.LoadSignature(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse LoadSignature(eSign.WebAPI.RpostService.FileUploadRequest FileMeta, System.IO.Stream FileByteStream) {
            eSign.WebAPI.RpostService.FileUploadMessage inValue = new eSign.WebAPI.RpostService.FileUploadMessage();
            inValue.FileMeta = FileMeta;
            inValue.FileByteStream = FileByteStream;
            eSign.WebAPI.RpostService.FileUploadResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).LoadSignature(inValue);
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.LoadSignatureFromBase64Response eSign.WebAPI.RpostService.RPostService.LoadSignatureFromBase64(eSign.WebAPI.RpostService.LoadSignatureFromBase64Request request) {
            return base.Channel.LoadSignatureFromBase64(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse LoadSignatureFromBase64(string AuthKey, string FileName, string FileContent) {
            eSign.WebAPI.RpostService.LoadSignatureFromBase64Request inValue = new eSign.WebAPI.RpostService.LoadSignatureFromBase64Request();
            inValue.AuthKey = AuthKey;
            inValue.FileName = FileName;
            inValue.FileContent = FileContent;
            eSign.WebAPI.RpostService.LoadSignatureFromBase64Response retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).LoadSignatureFromBase64(inValue);
            return retVal.LoadSignatureFromBase64Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.AuthenticateUserResponse eSign.WebAPI.RpostService.RPostService.AuthenticateUser(eSign.WebAPI.RpostService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public eSign.WebAPI.RpostService.AuthorizationResponse AuthenticateUser(string UserID, string Password) {
            eSign.WebAPI.RpostService.AuthenticateUserRequest inValue = new eSign.WebAPI.RpostService.AuthenticateUserRequest();
            inValue.UserID = UserID;
            inValue.Password = Password;
            eSign.WebAPI.RpostService.AuthenticateUserResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).AuthenticateUser(inValue);
            return retVal.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.AuthenticateEnterpriseResponse eSign.WebAPI.RpostService.RPostService.AuthenticateEnterprise(eSign.WebAPI.RpostService.AuthenticateEnterpriseRequest request) {
            return base.Channel.AuthenticateEnterprise(request);
        }
        
        public eSign.WebAPI.RpostService.AuthorizationResponse AuthenticateEnterprise(string EnterpriseID, string Password, string APIKey, string CustomerAccount) {
            eSign.WebAPI.RpostService.AuthenticateEnterpriseRequest inValue = new eSign.WebAPI.RpostService.AuthenticateEnterpriseRequest();
            inValue.EnterpriseID = EnterpriseID;
            inValue.Password = Password;
            inValue.APIKey = APIKey;
            inValue.CustomerAccount = CustomerAccount;
            eSign.WebAPI.RpostService.AuthenticateEnterpriseResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).AuthenticateEnterprise(inValue);
            return retVal.AuthenticateEnterpriseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.ForgotPasswordResponse eSign.WebAPI.RpostService.RPostService.ForgotPassword(eSign.WebAPI.RpostService.ForgotPasswordRequest request) {
            return base.Channel.ForgotPassword(request);
        }
        
        public eSign.WebAPI.RpostService.AuthorizationResponse ForgotPassword(string UserId) {
            eSign.WebAPI.RpostService.ForgotPasswordRequest inValue = new eSign.WebAPI.RpostService.ForgotPasswordRequest();
            inValue.UserId = UserId;
            eSign.WebAPI.RpostService.ForgotPasswordResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).ForgotPassword(inValue);
            return retVal.ForgotPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.ChangePasswordResponse eSign.WebAPI.RpostService.RPostService.ChangePassword(eSign.WebAPI.RpostService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public eSign.WebAPI.RpostService.AuthorizationResponse ChangePassword(string UserId, string OldPassword, string NewPassword, string ConfirmPassword) {
            eSign.WebAPI.RpostService.ChangePasswordRequest inValue = new eSign.WebAPI.RpostService.ChangePasswordRequest();
            inValue.UserId = UserId;
            inValue.OldPassword = OldPassword;
            inValue.NewPassword = NewPassword;
            inValue.ConfirmPassword = ConfirmPassword;
            eSign.WebAPI.RpostService.ChangePasswordResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).ChangePassword(inValue);
            return retVal.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.LogoutResponse eSign.WebAPI.RpostService.RPostService.Logout(eSign.WebAPI.RpostService.LogoutRequest request) {
            return base.Channel.Logout(request);
        }
        
        public eSign.WebAPI.RpostService.AuthorizationResponse Logout(string AuthKey) {
            eSign.WebAPI.RpostService.LogoutRequest inValue = new eSign.WebAPI.RpostService.LogoutRequest();
            inValue.AuthKey = AuthKey;
            eSign.WebAPI.RpostService.LogoutResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).Logout(inValue);
            return retVal.LogoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.ResendActivationLinkResponse eSign.WebAPI.RpostService.RPostService.ResendActivationLink(eSign.WebAPI.RpostService.ResendActivationLinkRequest request) {
            return base.Channel.ResendActivationLink(request);
        }
        
        public eSign.WebAPI.RpostService.AuthorizationResponse ResendActivationLink(string UserId) {
            eSign.WebAPI.RpostService.ResendActivationLinkRequest inValue = new eSign.WebAPI.RpostService.ResendActivationLinkRequest();
            inValue.UserId = UserId;
            eSign.WebAPI.RpostService.ResendActivationLinkResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).ResendActivationLink(inValue);
            return retVal.ResendActivationLinkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSign.WebAPI.RpostService.ChangeDisplayNameResponse eSign.WebAPI.RpostService.RPostService.ChangeDisplayName(eSign.WebAPI.RpostService.ChangeDisplayNameRequest request) {
            return base.Channel.ChangeDisplayName(request);
        }
        
        public eSign.WebAPI.RpostService.ServiceResponse ChangeDisplayName(string AuthKey, string DisplayName) {
            eSign.WebAPI.RpostService.ChangeDisplayNameRequest inValue = new eSign.WebAPI.RpostService.ChangeDisplayNameRequest();
            inValue.AuthKey = AuthKey;
            inValue.DisplayName = DisplayName;
            eSign.WebAPI.RpostService.ChangeDisplayNameResponse retVal = ((eSign.WebAPI.RpostService.RPostService)(this)).ChangeDisplayName(inValue);
            return retVal.ChangeDisplayNameResult;
        }
    }
}
